In [1]:
import numpy as np

In [2]:
matrix_fixed = np.random.randint(1, 51, (3, 3))

# Display the matrix with fixed seed
print("Matrix with fixed seed:")
print(matrix_fixed)


Matrix with fixed seed:
[[17 43  2]
 [13 31  4]
 [20 23 46]]


In [3]:
matrix_random = np.random.randint(1, 51, (3, 3))

# Display the matrix without a fixed seed
print("\nMatrix without fixed seed:")
print(matrix_random)


Matrix without fixed seed:
[[ 2 44 38]
 [34 41 14]
 [10 16 22]]
